# Generated by Django 5.0.8 on 2025-07-27 05:34

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Control anual',
                'verbose_name_plural': 'Controles anuales',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app_backend.patient',),
        ),
    ]
