# Generated by Django 5.0.8 on 2026-03-10 02:57

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'TB_BACKEND_BRAND',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'TB_BACKEND_CATEGORY',
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='Detalle')),
                ('value', models.CharField(default='', max_length=1000, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Detalle de empresa',
                'verbose_name_plural': 'Detalles de empresa',
                'db_table': 'TB_CONFIGURATION',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('first_name', models.CharField(max_length=250, verbose_name='Nombre completo')),
                ('surname', models.CharField(max_length=100, verbose_name='Apellido paterno')),
                ('second_surname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido materno')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('document_number', models.CharField(max_length=25, verbose_name='Número de documento')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Genero')),
                ('phone_or_cellular', models.CharField(blank=True, max_length=150, null=True, verbose_name='Telefono o Celular')),
                ('direction', models.CharField(blank=True, max_length=500, null=True, verbose_name='Dirección')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'TB_BACKEND_PATIENT',
            },
        ),
        migrations.CreateModel(
            name='TypeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('short_name', models.CharField(max_length=25, unique=True, verbose_name='Nombre corto')),
                ('long_name', models.CharField(max_length=100, verbose_name='Nombre largo')),
                ('type_patron', models.IntegerField(choices=[(0, 'Numerico'), (1, 'Alfanumerico')], verbose_name='Tipo de patron')),
                ('taxpayer_type', models.IntegerField(choices=[(0, 'Documento para nacionales solamente'), (1, 'Documento para extranjeros solamente'), (2, 'Documento para nacionales y extranjeros')], verbose_name='Tipo contribuyente')),
                ('type_length', models.IntegerField(choices=[(0, 'Exacta'), (1, 'Inexacta')])),
                ('length', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tipo de documento',
                'verbose_name_plural': 'Tipos de documentos',
                'db_table': 'TB_BACKEND_TYPE_DOCUMENT',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre del Producto')),
                ('code', models.CharField(blank=True, max_length=150, null=True, verbose_name='Código del Producto')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('unit_price', models.FloatField(blank=True, null=True, verbose_name='Precio (S/)')),
                ('unit_measure', models.CharField(choices=[('UNIDAD', 'UNIDAD'), ('PAR', 'PAR'), ('CAJA', 'CAJA'), ('BOTELLA', 'BOTELLA'), ('PAQUETE', 'PAQUETE'), ('METRO', 'METRO'), ('LITRO', 'LITRO')], max_length=7, verbose_name='Unidad de Medida')),
                ('initial_stock', models.IntegerField(default=0, verbose_name='Stock Inicial')),
                ('status', models.BooleanField(default=True, verbose_name='Estado del Producto')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_backend.brand', verbose_name='Marca')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_backend.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'TB_BACKEND_PRODUCT',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('prescription_number', models.CharField(max_length=6, unique=True, verbose_name='Número de recetario')),
                ('date_of_issue', models.DateField(verbose_name='Fecha de emisión')),
                ('right_eye_spherical_distance_far', models.FloatField(blank=True, null=True, verbose_name='O.D. Esferico')),
                ('right_eye_cylinder_distance_far', models.FloatField(blank=True, null=True, verbose_name='O.D. Cilindro')),
                ('right_eye_axis_distance_far', models.FloatField(blank=True, null=True, verbose_name='O.D. Eje')),
                ('left_eye_spherical_distance_far', models.FloatField(blank=True, null=True, verbose_name='O.I. Esferico')),
                ('left_eye_cylinder_distance_far', models.FloatField(blank=True, null=True, verbose_name='O.I. Cilindro')),
                ('left_eye_axis_distance_far', models.FloatField(blank=True, null=True, verbose_name='O.I. Eje')),
                ('pupillary_distance_far', models.FloatField(blank=True, null=True, verbose_name='Distancia pupilar')),
                ('right_eye_spherical_distance_near', models.FloatField(blank=True, null=True, verbose_name='O.D. Esferico')),
                ('right_eye_cylinder_distance_near', models.FloatField(blank=True, null=True, verbose_name='O.D. Cilindro')),
                ('right_eye_axis_distance_near', models.FloatField(blank=True, null=True, verbose_name='O.D. Eje')),
                ('left_eye_spherical_distance_near', models.FloatField(blank=True, null=True, verbose_name='O.I. Esferico')),
                ('left_eye_cylinder_distance_near', models.FloatField(blank=True, null=True, verbose_name='O.I. Cilindro')),
                ('left_eye_axis_distance_near', models.FloatField(blank=True, null=True, verbose_name='O.I. Eje')),
                ('pupillary_distance_near', models.FloatField(blank=True, null=True, verbose_name='Distancia pupilar')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('instruction', models.TextField(blank=True, null=True, verbose_name='Instrucciones')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_backend.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Recetario',
                'verbose_name_plural': 'Recetarios',
            },
        ),
        migrations.CreateModel(
            name='SalesLines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('quantity', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('unit_price', models.FloatField(blank=True, null=True, verbose_name='Precio unitario')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='Importe')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_backend.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Linea de venta',
                'verbose_name_plural': 'Lineas de ventas',
                'db_table': 'TB_BACKEND_SALES_LINES',
            },
        ),
        migrations.CreateModel(
            name='SalesTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('ballot_number', models.CharField(max_length=10, unique=True, verbose_name='Número de boleta')),
                ('date_of_issue', models.DateField(verbose_name='Fecha de emisión')),
                ('payer_name', models.CharField(blank=True, help_text='Llenar solo si quien paga NO es el paciente.', max_length=255, null=True, verbose_name='Nombre del Pagador/Tutor')),
                ('sales_total', models.FloatField(blank=True, null=True, verbose_name='Total de ventas')),
                ('observation', models.TextField(blank=True, null=True)),
                ('is_disabled', models.BooleanField(default=False, verbose_name='Anulado')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_backend.patient', verbose_name='Paciente')),
                ('product', models.ManyToManyField(related_name='product', through='app_backend.SalesLines', to='app_backend.product')),
            ],
            options={
                'verbose_name': 'Boleta de venta',
                'verbose_name_plural': 'Boletas de ventas',
                'db_table': 'TB_BACKEND_SALES_TICKET',
                'ordering': ['-ballot_number'],
            },
        ),
        migrations.AddField(
            model_name='saleslines',
            name='sales_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='app_backend.salesticket', verbose_name='Boleta'),
        ),
        migrations.AddField(
            model_name='patient',
            name='type_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_backend.typedocument', verbose_name='Tipo de documento'),
        ),
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together={('type_document', 'document_number')},
        ),
    ]
