# Generated by Django 5.0.8 on 2026-03-10 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='last_visit',
            field=models.DateField(blank=True, null=True, verbose_name='Última Visita'),
        ),
    ]
