# Generated by Django 5.0.8 on 2025-07-27 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='initial_stock',
            field=models.IntegerField(default=0, verbose_name='Stock Inicial'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Estado del Producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_backend.category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Código del Producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Nombre del Producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_measure',
            field=models.CharField(choices=[('UNIDAD', 'UNIDAD'), ('PAR', 'PAR')], max_length=7, verbose_name='Unidad de Medida'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Precio (S/)'),
        ),
    ]
