# Generated by Django 5.0.8 on 2025-07-27 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0002_product_initial_stock_product_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='code',
        ),
    ]
