# Generated by Django 5.0.8 on 2026-03-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0002_patient_last_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='last_visit',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Última Visita'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='left_eye_axis_distance_far',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='O.I. Eje'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='left_eye_axis_distance_near',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='O.I. Eje'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='left_eye_cylinder_distance_far',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='O.I. Cilindro'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='left_eye_cylinder_distance_near',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='O.I. Cilindro'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='left_eye_spherical_distance_far',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='O.I. Esferico'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='left_eye_spherical_distance_near',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='O.I. Esferico'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='pupillary_distance_far',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Distancia pupilar'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='pupillary_distance_near',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Distancia pupilar'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='right_eye_axis_distance_far',
            field=models.CharField(blank=True, default=1, max_length=6, verbose_name='O.D. Eje'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='right_eye_axis_distance_near',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='O.D. Eje'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='right_eye_cylinder_distance_far',
            field=models.CharField(blank=True, default=1, max_length=6, verbose_name='O.D. Cilindro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='right_eye_cylinder_distance_near',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='O.D. Cilindro'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='right_eye_spherical_distance_far',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='O.D. Esferico'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='right_eye_spherical_distance_near',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='O.D. Esferico'),
        ),
    ]
