# Generated by Django 5.0.8 on 2025-07-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0003_remove_category_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Código del Producto'),
        ),
    ]
