# Generated by Django 5.0.8 on 2026-03-12 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0003_alter_patient_last_visit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='right_eye_axis_distance_far',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='O.D. Eje'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='right_eye_cylinder_distance_far',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='O.D. Cilindro'),
        ),
    ]
