# Generated by Django 5.0.8 on 2026-03-13 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0004_alter_recipe_right_eye_axis_distance_far_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha de la Cita')),
                ('time', models.TimeField(verbose_name='Hora de la Cita')),
                ('reason', models.CharField(max_length=255, verbose_name='Motivo (ej: Re-examen)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas u Observaciones')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Estado')),
                ('medium', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('presencial', 'Presencial'), ('llamada', 'Llamada'), ('otro', 'Otro')], default='whatsapp', max_length=20, verbose_name='Medio de Contacto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='app_backend.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['date', 'time'],
            },
        ),
    ]
