# Generated by Django 5.0.8 on 2025-08-01 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0004_alter_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Estado del Producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_measure',
            field=models.CharField(choices=[('UNIDAD', 'UNIDAD'), ('PAR', 'PAR'), ('CAJA', 'CAJA'), ('BOTELLA', 'BOTELLA'), ('PAQUETE', 'PAQUETE'), ('METRO', 'METRO'), ('LITRO', 'LITRO')], max_length=7, verbose_name='Unidad de Medida'),
        ),
    ]
