# Generated by Django 5.0.8 on 2026-03-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0005_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de la Cita'),
        ),
    ]
