# Generated by Django 5.0.8 on 2025-08-02 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0005_alter_product_status_alter_product_unit_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
