# Generated by Django 5.0.8 on 2026-03-16 00:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0006_alter_appointment_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de contacto')),
                ('medium', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('call', 'Llamada Telefónica'), ('sms', 'Mensaje de Texto')], default='whatsapp', max_length=20, verbose_name='Medio')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_contacts', to='app_backend.patient', verbose_name='Paciente')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts_performed', to=settings.AUTH_USER_MODEL, verbose_name='Personal que contactó')),
            ],
            options={
                'verbose_name': 'Contacto de Campaña',
                'verbose_name_plural': 'Contactos de Campaña',
                'ordering': ['-created'],
            },
        ),
    ]
