# Generated by Django 5.0.8 on 2025-08-03 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0006_patient_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Genero'),
        ),
    ]
