# Generated by Django 5.0.8 on 2025-08-04 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0007_recipe_is_active_alter_patient_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='is_disabled',
        ),
    ]
