# Generated by Django 5.0.8 on 2026-03-16 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0007_campaigncontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigncontact',
            name='is_converted',
            field=models.BooleanField(default=False, verbose_name='¿Generó venta?'),
        ),
        migrations.AddField(
            model_name='campaigncontact',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_conversions', to='app_backend.recipe'),
        ),
        migrations.AlterField(
            model_name='campaigncontact',
            name='medium',
            field=models.CharField(default='whatsapp', max_length=20, verbose_name='Medio'),
        ),
    ]
