# Generated by Django 5.0.8 on 2026-03-17 01:29

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0008_campaigncontact_is_converted_campaigncontact_recipe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Optica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Óptica')),
                ('ruc', models.CharField(max_length=20, unique=True, verbose_name='RUC / Identificación')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_opticas/')),
                ('plan', models.CharField(choices=[('ESENCIAL', 'Plan Esencial'), ('CRECIMIENTO', 'Plan Crecimiento'), ('PREMIUM', 'Plan Premium')], default='ESENCIAL', max_length=20)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
