# Generated by Django 5.0.8 on 2026-03-10 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0008_remove_recipe_is_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesticket',
            name='payer_name',
            field=models.CharField(blank=True, help_text='Llenar solo si quien paga NO es el paciente.', max_length=255, null=True, verbose_name='Nombre del Pagador/Tutor'),
        ),
        migrations.AlterField(
            model_name='saleslines',
            name='sales_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='app_backend.salesticket', verbose_name='Boleta'),
        ),
        migrations.AlterField(
            model_name='salesticket',
            name='is_disabled',
            field=models.BooleanField(default=False, verbose_name='Anulado'),
        ),
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together={('type_document', 'document_number')},
        ),
    ]
