# Generated by Django 5.0.8 on 2026-03-10 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0009_salesticket_payer_name_alter_saleslines_sales_ticket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesticket',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_backend.patient', verbose_name='Paciente'),
        ),
    ]
