# Generated by Django 5.0.8 on 2026-03-17 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0009_optica'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='optica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='app_backend.optica'),
        ),
        migrations.AddField(
            model_name='campaigncontact',
            name='optica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contactos_campana', to='app_backend.optica'),
        ),
        migrations.AddField(
            model_name='patient',
            name='optica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='app_backend.optica'),
        ),
        migrations.AddField(
            model_name='product',
            name='optica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='app_backend.optica'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='optica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recetarios', to='app_backend.optica'),
        ),
        migrations.AddField(
            model_name='salesticket',
            name='optica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='boletas_venta', to='app_backend.optica'),
        ),
    ]
