# Generated by Django 5.0.8 on 2026-03-17 01:35

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0010_appointment_optica_campaigncontact_optica_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador / Dueño'), ('OPTOMETRISTA', 'Optometrista'), ('VENTAS', 'Ventas / Recepción')], default='VENTAS', max_length=20)),
                ('optica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='app_backend.optica')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
