# Generated by Django 5.0.8 on 2026-03-21 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0011_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='optica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='app_backend.optica'),
        ),
    ]
