# Generated by Django 5.0.8 on 2026-03-21 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0012_category_optica'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='optica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='marcas', to='app_backend.optica'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=250, verbose_name='Nombre'),
        ),
    ]
